### ISSUE TITLE
Asynchronous Async Chunk Load! Blocking thread until it returns

### ISSUE THREAD

**Issue by B4TT3RY** [VolmitSoftware/React#284] opened 2018-04-01 03:41 UTC
```
[11:06:00] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[11:06:00] [React Reactor/WARN]: 	at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:54)
[11:06:00] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[11:06:00] [React Reactor/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[11:06:00] [React Reactor/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[11:06:00] [React Reactor/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[11:06:00] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:181)
[11:06:00] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:118)
[11:06:00] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:193)
[11:06:00] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:201)
[11:06:00] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:197)
[11:06:00] [React Reactor/WARN]: 	at com.volmit.react.util.W.blockFaces(W.java:604)
[11:06:00] [React Reactor/WARN]: 	at com.volmit.react.util.BlockFinder.tail(BlockFinder.java:30)
[11:06:00] [React Reactor/WARN]: 	at com.volmit.react.util.BlockFinder.follow(BlockFinder.java:20)
[11:06:00] [React Reactor/WARN]: 	at com.volmit.react.controller.FastDecayController$3$1.run(FastDecayController.java:131)
[11:06:00] [React Reactor/WARN]: 	at com.volmit.react.util.RQ.run(RQ.java:25)
```

PaperSpigot 1.12.2 (Build 1373)
React 6.3.1

**Comment by cyberpwnn** [comment] 2018-04-02 20:34
Duplicate of #254 #281

**Closed by cyberpwnn** 2018-04-02 20:34 UTC
Labels: R6, bug

**Comment by B4TT3RY** [comment] 2018-04-03 03:18
@cyberpwnn But i'm using 6.3.1, This error does not occur at server startup. It comes out during play.

**Comment by B4TT3RY** [comment] 2018-04-03 09:21
```
Search "java.lang.illegalstateexception" (21 hits in 1 file)
  C:\Users\Administrator\Desktop\latest.log (21 hits)
	Line 1280: [10:18:48] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 1921: [14:18:31] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 1941: [14:18:32] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 1958: [14:18:32] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 1978: [14:18:32] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 1998: [14:18:34] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 2675: [15:10:55] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 2695: [15:10:55] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 2715: [15:10:55] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 2735: [15:10:55] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 2755: [15:10:55] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 2775: [15:10:55] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 3003: [15:33:49] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 3185: [16:02:04] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 3206: [16:03:04] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 3223: [16:03:04] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 3243: [16:03:04] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 3263: [16:03:06] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 3283: [16:03:08] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 3309: [16:03:53] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
	Line 4797: [18:20:33] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
```

**Comment by B4TT3RY** [comment] 2018-04-03 12:49
@cyberpwnn @lucas2107

**Comment by lucas2107** [comment] 2018-04-03 16:07
As cyberpwn say, duplicate of #281
