### ISSUE TITLE
1.15.2 SuperSampler Crash

### ISSUE THREAD

**Issue by Flo122** [VolmitSoftware/React#544] opened 2020-06-10 17:01 UTC
**Describe the bug**

On Serverstart i got a Error with SuperSampler Crash
Tried to unload many other plugins worked sometimes 

**To Reproduce**
1. 
Start Server 
React Load 
All other plugins load 
Server load done 
React Super Sampler Crash restart react
SS don't respond for 25s

If the plugin loaded one time fully without crash it's working to archive this we unload random plugins and try to load react sometime it's working 

If we start chunk purging and restart react the plugin stop working 
With supersampler crash 

Im pretty curious there is no special plugin who interrupt react from load 
Sometimes it's leader heads the other time it's citizen and so on 

**Server and Plugin Informations**
 - Installed plugins: world guard, async world edit, hayperverse, matrix, vote plugin, leader heads, citizen 
 - React Version: Newest
 - Paper Spigot 1.15.2
 - Windows Server 2012

**Comment by relavis** [comment] 2020-07-12 07:25
Duplicate of #538

**Closed by relavis** 2020-07-12 07:25 UTC
Labels: bug
