### ISSUE TITLE
Super Sampler Spam & Possible Crash

### ISSUE THREAD

**Issue by LoXR** [VolmitSoftware/React#236] opened 2018-03-13 13:17 UTC
Was told to revert back to react 5 due to these.

Whats happend?
In the console it had spammed this:
[08:44:45] [Server thread/INFO]: React: Super Sampler did not start correctly. Resetting
[08:44:48] [Server thread/INFO]: React: Language: enUS

And shortly after it had crashed my server with this in the crash reports.
Crash report: https://pastebin.com/2XBN1XkJ

**Comment by lucas2107** [comment] 2018-03-13 17:13
Duplicate of #222

**Closed by lucas2107** 2018-03-13 17:13 UTC
Labels: R6, duplicate

**Comment by cyberpwnn** [comment] 2018-03-13 20:15
It's a standard paperspigot crash. Maybe it saw a ghost.
