### ISSUE TITLE
Link to download classmexer-1.0.jar is down

### ISSUE THREAD

**Issue by Kira07** [VolmitSoftware/React#522] opened 2019-09-17 18:59 UTC
**Describe the bug**
The command "react installagent" returns "Download failed" because the download URL is down (http://nexus.volmit.com/content/repositories/thirdparty/com/javamex/classmexer/1.0/classmexer-1.0.jar)

**To Reproduce**
Type "react installagent"

**Expected behavior**
A successful download.

**Comment by DavidRockin** [comment] 2019-09-17 19:09
Duplicate of #517

**Closed by DavidRockin** 2019-09-17 19:09 UTC
Labels: bug
