### ISSUE TITLE
Chunk is bugging

### ISSUE THREAD

**Issue by florianokaplo** [VolmitSoftware/React#351] opened 2018-05-16 13:31 UTC
Hey, my problem is since i installed React on my Server the Chunk 0 ~ 0 is always a ghost chunk! I tried to fix this with React but it didn't work. So I dan't use React on my Server.

**Comment by lucas2107** [comment] 2018-05-16 16:37
Duplicate of #260

**Closed** 2018-05-16 16:37 UTC
Labels: duplicate
