### ISSUE TITLE
Error on doing nothing!

### ISSUE THREAD

**Issue by Clasher31HD** [VolmitSoftware/React#441] opened 2018-07-23 22:35 UTC
```
[00:28:48 WARN]: Exception in thread "Craft Scheduler Thread - 2"
[00:28:48 WARN]: org.apache.commons.lang.UnhandledException: Plugin React v6.569 generated an exception while executing task 214
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.volmit.react.util.Platform
        at com.volmit.react.util.Platform$CPU.getLiveProcessCPULoad(Platform.java:232)
        at com.volmit.react.sampler.SampleCPU$2.run(SampleCPU.java:56)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```
(from https://pastebin.com/7mLJ7nnk)

**Comment by cyberpwnn** [comment] 2018-07-24 07:58
Perhaps your server is on a virtual machine which has denied react to ask for cpu information? Ill add something for that.

**Comment by SwiftSwamp** [comment] 2019-08-15 05:22
Closing as this was likely fixed in the latest updates... and the issue is old. Please reopen if the issue continues.

**Closed by SwiftSwamp** 2019-08-15 05:22 UTC
Labels: 1.8, bug
