### ISSUE TITLE
1.8 chunck bug #2

### ISSUE THREAD

**Issue by Acenox** [VolmitSoftware/React#290] opened 2018-04-07 14:51 UTC
Hi, 

I'm using the latest version of React on my spigot-1.8.8 server and I still have the bug of chunk ... It had to be fix there are some updates: https://www.spigotmc.org/resources/react-smart-server-performance.21057/update?update=217528

![image](https://user-images.githubusercontent.com/21250318/38456326-d7c3d8de-3a83-11e8-82c5-2e4c06a04200.png)

ps: as soon as I uninstall React, I have no problem + I have no error in the console.

Best regards,

**Comment by lucas2107** [comment] 2018-04-07 15:01
Duplicate of #260

**Closed by lucas2107** 2018-04-07 15:01 UTC
