### ISSUE TITLE
NullPointerException on InventoryMoveItemEvent 

### ISSUE THREAD

**Issue by NmChris** [VolmitSoftware/React#509] opened 2019-07-25 05:08 UTC
Server version = git-Paper-146 (MC: 1.14.4)
React version: 6.612

>.... [00:06:34 ERROR]: Could not pass event InventoryMoveItemEvent to React v6.612
java.lang.NullPointerException: null

https://paste.ee/p/MYJ0D

**Comment by DavidRockin** [comment] 2019-07-27 22:59
Duplicate of #508

**Closed by DavidRockin** 2019-07-27 22:59 UTC
