### ISSUE TITLE
Stacked mobs high hp

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#341] opened 2018-05-10 08:35 UTC
Stacked mobs don't want to die :/

Paperspigot 1.8.8
React 6.5.3

**Comment by cyberpwnn** [comment] 2018-05-10 17:45
Correct 
![image](https://user-images.githubusercontent.com/10619135/39884583-523643b6-5458-11e8-868b-514cb541b32c.png)
https://minecraft.gamepedia.com/Blaze

**Comment by lucas2107** [comment] 2018-05-10 20:48
Stacked mobs are just invincible.

**Comment by lucas2107** [comment] 2018-05-11 16:42
#342 ==> https://www.youtube.com/watch?v=fI15n7RE8LQ&feature=youtu.be

Bugs:

* Stacked mobs are invincible
* Mobs despawn randomly
* Falling Mobs are glitched when they die

**Comment by cyberpwnn** [comment] 2018-05-15 09:04
Does this still happen on the latest version? Im pretty sure i fixed it.

**Comment by cyberpwnn** [comment] 2018-05-17 09:55
Fixed in 6.543

**Comment by lucas2107** [comment] 2018-05-20 17:53
Still not fixed in 6.544

https://streamable.com/u1z63 (Reported by M8wqp6Sl11)

**Comment by cyberpwnn** [comment] 2018-05-28 13:47
Does anyone have reproduction steps? Because i cannot reproduce it.

**Comment by lucas2107** [comment] 2018-05-28 16:04
Use paper 1.8.8 @cyberpwnn

**Comment by cyberpwnn** [comment] 2018-05-30 00:55
Fixed in 6.552

**Closed by cyberpwnn** 2018-05-30 00:55 UTC
Labels: bug, confirmed, missing information
