### ISSUE TITLE
Stack mob type Cave_Spider is not working

### ISSUE THREAD

**Issue by WindUnwaken** [VolmitSoftware/React#419] opened 2018-06-30 05:43 UTC
Stack mob in each type of mob works well, but not Cave_Spider

**Comment by cyberpwnn** [comment] 2018-06-30 10:48
Are there any exceptions? Send your allow-stacking list

**Comment by WindUnwaken** [comment] 2018-06-30 11:15
https://pastebin.com/ZZbf4pBX

**Comment by cyberpwnn** [comment] 2018-07-07 20:11
Cant seem to reproduce it.

**Comment by SwiftSwamp** [comment] 2019-08-15 05:23
Closing as this was likely fixed in the latest updates... and the issue is old. Please reopen if the issue continues.

**Closed by SwiftSwamp** 2019-08-15 05:23 UTC
Labels: bug, missing information
