### ISSUE TITLE
Two Errors in console: SuperSampler Crashing + other

### ISSUE THREAD

**Issue by draius** [VolmitSoftware/React#541] opened 2020-05-11 00:12 UTC
**Describe the bug**
Upon logging into the server, nothing else loads when I try to execute commands, ranks, plugins) until about 15-20 seconds later after looking in console once everything loaded in I saw that the supersampler crashed as I was attempting to execute things: https://prnt.sc/sefadg
 
**To Reproduce**
1. Login
2. Attempt to execute command
3. Chat messages load, but are missing proper formatting
4. Commands dont execute until the spike is over

**Expected behavior**
No spikes, proper loading upon logging in

**Screenshots or Video Recordings**
 http://bit.ly/1oSiM6C
https://prnt.sc/sefadg
**Server and Plugin Informations**
 - Installed plugins: LuckPerms, FAWE, ViaVersion, WorldBorder, ProtocolLib, React, and other custom plugins
 - React Version: 6.618
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: Custom 1.8 Spigot
 - Operating System (if applicable): Linux

**Additional context**
Add any other context about the problem here, server timings reports, React dump information, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by draius** [comment] 2020-05-11 19:13
https://prnt.sc/sevywt - This is also an error that popped up in the chat

**Comment by relavis** [comment] 2020-07-12 07:25
Duplicate of #538

**Closed by relavis** 2020-07-12 07:25 UTC
Labels: bug
