### ISSUE TITLE
[Bug] Error with commands being dispatched async

### ISSUE THREAD

**Issue by TheWranger** [VolmitSoftware/React#398] opened 2018-06-22 05:54 UTC
https://pastebin.com/Ng36FX23
Get this whenever I get a message from React telling me that the server is frozen due to a plugin.
Running PaperSpigot 1.12.2 (1466)

**Comment by lucas2107** [comment] 2018-06-22 10:28
Duplicate of #395

**Closed by lucas2107** 2018-06-22 10:28 UTC
