### ISSUE TITLE
React failed to receive PacketPlayInKeepAlive

### ISSUE THREAD

**Issue by EthanTG** [VolmitSoftware/React#243] opened 2018-03-15 21:03 UTC
http://paste.volmit.com/raw/bekebipixi

Happened only one time after a kick with AdvancedBan.

Issue #242 is missing more than half the error (I'm bad at copying) :/

also it's my error so nobody take credit
---
+1 if you've had similar issues or support me

**Comment by lucas2107** [comment] 2018-03-15 21:05
duplicate of #242

**Comment by Puretie** [comment] 2018-03-15 21:08
Continuation of #242

**Comment by cyberpwnn** [comment] 2018-03-16 02:53
Protocollib Version
Minecraft Version
Spigot? Paper? What is the flavor?

**Comment by cyberpwnn** [comment] 2018-03-16 04:36
Fixed in 6.2.1

**Closed by cyberpwnn** 2018-03-16 04:36 UTC
Labels: R6, bug, missing information

**Comment by EthanTG** [comment] 2018-03-16 19:28
you apparently answered your own questions :P
