### ISSUE TITLE
Lag problem

### ISSUE THREAD

**Issue by p82183645** [VolmitSoftware/React#399] opened 2018-06-22 07:12 UTC
![image](https://user-images.githubusercontent.com/5382252/41762785-7f8435ec-762e-11e8-8f80-bd85aba479db.png)

Will always appear this on my console
The server will have lag

I use the latest version recat
Paper 1.12.2

**Comment by lucas2107** [comment] 2018-06-22 10:28
Duplicate of #395

**Closed by lucas2107** 2018-06-22 10:28 UTC
