### ISSUE TITLE
(BUG) Random console error

### ISSUE THREAD

**Issue by johnsoncui02** [VolmitSoftware/React#499] opened 2019-05-08 19:03 UTC
Paper Spigot 1.13.2 #629
React 6.610
Cause of the issue: Unknown

`[14:40:13 WARN]: [React] Plugin React v6.61 generated an exception while executing task 7046932
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_202]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_202]
at primal.lang.collection.GList.<init>(GList.java:87) ~[?:?]
at primal.lang.collection.GMap.k(GMap.java:122) ~[?:?]
at com.volmit.react.controller.EntityCullController$1.run(EntityCullController.java:144) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-623]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-623]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-623]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]`

**Comment by jascotty2** [comment] 2019-05-14 11:47
Duplicate of #491

**Comment by DavidRockin** [comment] 2019-07-09 03:36
Fixed in #498

**Closed by DavidRockin** 2019-07-09 03:36 UTC
Labels: 1.13, bug
