### ISSUE TITLE
World Bug (v6.3)

### ISSUE THREAD

**Issue by GalaxyEaterGR** [VolmitSoftware/React#280] opened 2018-03-28 21:14 UTC
I removed the FAWE plugin and stills has this bug on the world chunk loader... please fix as soon as possible because this makes the plugin useless for a factions server

Photo: http://prntscr.com/ixqqxp

**Comment by lucas2107** [comment] 2018-03-28 21:50
Duplicate of #260

**Closed by lucas2107** 2018-03-28 21:50 UTC
Labels: duplicate
