### ISSUE TITLE
React monitor error

### ISSUE THREAD

**Issue by Sikatsu** [VolmitSoftware/React#485] opened 2019-02-13 12:27 UTC
Error when using the monitor: https://pastebin.com/ZVrkmJiW

**Comment by cyberpwnn** [comment] 2019-02-16 00:58
Missing information.

Use -XX:-OmitStackTraceInFastThrow in your launch args.

**Comment by Sikatsu** [comment] 2019-02-16 09:09
I'm not on a dedicated server. How do I do this?

Op za 16 feb. 2019 01:58 schreef Dan <notifications@github.com:

**Comment by cyberpwnn** [comment] 2019-02-16 11:02
Just the jvm start flags. If you cant get that info, i cant possibly know where the problem is coming from.

**Comment by Sikatsu** [comment] 2019-02-27 10:12
I haven't seen this error anymore.

**Comment by cyberpwnn** [comment] 2019-02-27 18:01
Alright, ill close it for now then

**Closed by cyberpwnn** 2019-02-27 18:01 UTC
Labels: 1.13, missing information
