### ISSUE TITLE
The new Alerts for locks/etc disables Monitor

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#400] opened 2018-06-23 01:27 UTC
The monitor shuts off when the new server lock alerts go off. First time it has happened, hasn't been recreated yet.
Spigot 1.12.2 most recent version
React 6.56

https://i.imgur.com/j4eoExQ.png

**Comment by cyberpwnn** [comment] 2018-06-23 05:20
Well as shown, react caught the spike as a garbage collector, if the monitor was **interrupted** than that would be because of gc as it performs a STW (stop the world) which freezes everything.

If it actually disabled monitoring, it would have to send the message to you... Did the monitor come back or did you have to manually invoke the command again?

**Comment by CaptainAmpersand** [comment] 2018-06-23 05:22
Manually invoke. I haven’t had to re-enable it in a long time, that’s why I reported it as a bug :P

**Comment by SwiftSwamp** [comment] 2019-08-15 05:22
Closing as this was likely fixed in the latest updates... and the issue is old. Please reopen if the issue continues.

**Closed by SwiftSwamp** 2019-08-15 05:22 UTC
Labels: missing information
