### ISSUE TITLE
Periodically kicks player with Internal Error

### ISSUE THREAD

**Issue by i0xHeX** [VolmitSoftware/React#431] opened 2018-07-11 21:41 UTC
When you have map monitor enabled or that map on the wall, then sometimes it kicking with Internal Error: https://privatebin.net/?d7b169568b6b1555#hH8ayn3WekHSqvJCcx3AznMmbq6lU5PYJcWAoeZ0os8=
Issue detected using React 6.568
No such issues were detected on React 6.558

**Comment by i0xHeX** [comment] 2018-07-14 21:54
Not bungeecord, just simple test server

**Comment by SwiftSwamp** [comment] 2019-08-15 05:22
Closing as this was likely fixed in the latest updates... and the issue is old. Please reopen if the issue continues.

**Closed by SwiftSwamp** 2019-08-15 05:22 UTC
Labels: ancient, bug
