### ISSUE TITLE
Failed to save Entity Stack Cache

### ISSUE THREAD

**Issue by lawnmeower** [VolmitSoftware/React#440] opened 2018-07-23 19:10 UTC
The following warning happens upon shutting down my server (or react). I'm using Spigot 1.12.2, not 1.13.

```
[15:05:38] [Server thread/INFO]: [React] Disabling React v6.569
[15:05:38] [React Monitor/WARN]: Exception in thread "React Monitor" 
[15:05:38] [React Monitor/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[15:05:38] [React Monitor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:413)
[15:05:38] [React Monitor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:148)
[15:05:38] [React Monitor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleAsyncRepeatingTask(CraftScheduler.java:144)
[15:05:38] [React Monitor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleAsyncDelayedTask(CraftScheduler.java:118)
[15:05:38] [React Monitor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleAsyncDelayedTask(CraftScheduler.java:101)
[15:05:38] [React Monitor/WARN]: 	at com.volmit.react.util.RQ.run(RQ.java:55)
[15:05:38] [React Monitor/WARN]: 	at com.volmit.react.util.A.<init>(A.java:7)
[15:05:38] [React Monitor/WARN]: 	at com.volmit.react.util.TPSMonitor$3.<init>(TPSMonitor.java:172)
[15:05:38] [React Monitor/WARN]: 	at com.volmit.react.util.TPSMonitor.run(TPSMonitor.java:171)
[15:05:38] [Server thread/WARN]: java.io.FileNotFoundException: plugins\React\cache\stack-cache.ulf (The system cannot find the path specified)
[15:05:38] [Server thread/WARN]: 	at java.io.FileOutputStream.open0(Native Method)
[15:05:38] [Server thread/WARN]: 	at java.io.FileOutputStream.open(Unknown Source)
[15:05:38] [Server thread/WARN]: 	at java.io.FileOutputStream.<init>(Unknown Source)
[15:05:38] [Server thread/WARN]: 	at java.io.FileOutputStream.<init>(Unknown Source)
[15:05:38] [Server thread/WARN]: 	at com.volmit.react.api.StackData.save(StackData.java:63)
[15:05:38] [Server thread/WARN]: 	at com.volmit.react.controller.EntityStackController.saveCacheFinal(EntityStackController.java:142)
[15:05:38] [Server thread/WARN]: 	at com.volmit.react.controller.EntityStackController.stop(EntityStackController.java:158)
[15:05:38] [Server thread/WARN]: 	at com.volmit.react.ReactPlugin.onDisable(ReactPlugin.java:336)
[15:05:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[15:05:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[15:05:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422)
[15:05:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415)
[15:05:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:349)
[15:05:38] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465)
[15:05:38] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613)
[15:05:38] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by SwiftSwamp** [comment] 2019-08-15 05:22
Closing as this was likely fixed in the latest updates... and the issue is old. Please reopen if the issue continues.

**Closed by SwiftSwamp** 2019-08-15 05:22 UTC
Labels: 1.12, bug
