### ISSUE TITLE
React Sampler crashed

### ISSUE THREAD

**Issue by Sikatsu** [VolmitSoftware/React#481] opened 2019-02-07 20:33 UTC
This happens very often.

07.02 21:32:43 [Server] Startup Done (21.355s)! For help, type "help"
07.02 21:32:43 [Server] INFO Starting GS4 status listener
07.02 21:32:43 [Server] INFO Query running on 193.70.117.133:25565
07.02 21:32:43 [Server] INFO React Supersampler has crashed. Reloading React.
07.02 21:32:43 [Server] INFO SS has not responded for over 27.95s

**Comment by lucas2107** [comment] 2019-02-08 11:07
Hi,

We need more informations like server version and your React Version.

**Comment by Sikatsu** [comment] 2019-02-08 11:07
1.13.2, latest React version altho it has been around before cyberpwn started to work on 1.13 fixes.

**Comment by Sikatsu** [comment] 2019-02-13 12:28
Am I the only one having this issue? It nearly occurs on every startup..

**Comment by cyberpwnn** [comment] 2019-02-16 00:59
Backup your config and try to gen a new one. See if it still happens

**Comment by Sikatsu** [comment] 2019-02-16 09:09
Already did for the culling list new defaults.

Op za 16 feb. 2019 01:59 schreef Dan <notifications@github.com:

**Comment by Sikatsu** [comment] 2019-02-27 10:11
Now it crashed randomly, not on server startup.

27.02 10:49:56 [Server] INFO React Supersampler has crashed. Reloading React.
27.02 10:49:56 [Server] INFO SS has not responded for over 18.96s
27.02 10:49:57 [Server] INFO Selected R1_13
27.02 10:49:57 [Server] INFO React: Language: enUS
27.02 10:49:57 [Server] INFO 1.13.2

**Comment by DavidRockin** [comment] 2019-07-30 21:02
It appears to crash when the server hangs. If you are still experiencing this issue, can you swap to Paperspigot, you will receive dumps when a thread hangs.

For my personal reference, unrelated to React:

```
 [20:57:18 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:57:18 ERROR]: The server has not responded for 10 seconds! Creating thread dump
[20:57:18 ERROR]: ------------------------------
[20:57:18 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[20:57:18 ERROR]: ------------------------------
[20:57:18 ERROR]: Current Thread: Server thread
[20:57:18 ERROR]: PID: 22 | Suspended: false | Native: false | State: RUNNABLE
[20:57:18 ERROR]: Stack:
[20:57:18 ERROR]: org.bukkit.craftbukkit.v1_12_R1.util.WeakCollection$1.hasNext(WeakCollection.java:81)
[20:57:18 ERROR]: org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftScoreboardManager.getScoreboardScores(CraftScoreboardManager.java:104)
[20:57:18 ERROR]: net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:429)
[20:57:18 ERROR]: net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:366)
[20:57:18 ERROR]: net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:145)
[20:57:18 ERROR]: net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273)
[20:57:18 ERROR]: net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
[20:57:18 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948)
[20:57:18 ERROR]: net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[20:57:18 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[20:57:18 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[20:57:18 ERROR]: java.lang.Thread.run(Thread.java:748)
[20:57:18 ERROR]: ------------------------------
[20:57:18 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:57:18 ERROR]: ------------------------------
[20:57:23 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:57:23 ERROR]: The server has not responded for 15 seconds! Creating thread dump
[20:57:23 ERROR]: ------------------------------
[20:57:23 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[20:57:23 ERROR]: ------------------------------
[20:57:23 ERROR]: Current Thread: Server thread
[20:57:23 ERROR]: PID: 22 | Suspended: false | Native: false | State: RUNNABLE
[20:57:23 ERROR]: Stack:
[20:57:23 ERROR]: org.bukkit.craftbukkit.v1_12_R1.util.WeakCollection$1.hasNext(WeakCollection.java:81)
[20:57:23 ERROR]: org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftScoreboardManager.getScoreboardScores(CraftScoreboardManager.java:104)
[20:57:23 ERROR]: net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:429)
[20:57:23 ERROR]: net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:366)
[20:57:23 ERROR]: net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:145)
[20:57:23 ERROR]: net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273)
[20:57:23 ERROR]: net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
[20:57:23 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948)
[20:57:23 ERROR]: net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[20:57:23 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[20:57:23 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[20:57:23 ERROR]: java.lang.Thread.run(Thread.java:748)
[20:57:23 ERROR]: ------------------------------
[20:57:23 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:57:23 ERROR]: ------------------------------
[20:57:28 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:57:28 ERROR]: The server has not responded for 20 seconds! Creating thread dump
[20:57:28 ERROR]: ------------------------------
[20:57:28 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[20:57:28 ERROR]: ------------------------------
[20:57:28 ERROR]: Current Thread: Server thread
[20:57:28 ERROR]: PID: 22 | Suspended: false | Native: false | State: RUNNABLE
[20:57:28 ERROR]: Stack:
[20:57:28 ERROR]: org.bukkit.craftbukkit.v1_12_R1.util.WeakCollection$1.hasNext(WeakCollection.java:81)
[20:57:28 ERROR]: org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftScoreboardManager.getScoreboardScores(CraftScoreboardManager.java:104)
[20:57:28 ERROR]: net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:429)
[20:57:28 ERROR]: net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:366)
[20:57:28 ERROR]: net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:145)
[20:57:28 ERROR]: net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273)
[20:57:28 ERROR]: net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
[20:57:28 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948)
[20:57:28 ERROR]: net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[20:57:28 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[20:57:28 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[20:57:28 ERROR]: java.lang.Thread.run(Thread.java:748)
[20:57:28 ERROR]: ------------------------------
[20:57:28 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:57:28 ERROR]: ------------------------------
[20:57:33 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:57:33 ERROR]: The server has not responded for 25 seconds! Creating thread dump
[20:57:33 ERROR]: ------------------------------
[20:57:33 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[20:57:33 ERROR]: ------------------------------
[20:57:33 ERROR]: Current Thread: Server thread
[20:57:33 ERROR]: PID: 22 | Suspended: false | Native: false | State: RUNNABLE
[20:57:33 ERROR]: Stack:
[20:57:33 ERROR]: org.bukkit.craftbukkit.v1_12_R1.util.WeakCollection$1.hasNext(WeakCollection.java:81)
[20:57:33 ERROR]: org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftScoreboardManager.getScoreboardScores(CraftScoreboardManager.java:104)
[20:57:33 ERROR]: net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:429)
[20:57:33 ERROR]: net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:366)
[20:57:33 ERROR]: net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:145)
[20:57:33 ERROR]: net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273)
[20:57:33 ERROR]: net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
[20:57:33 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948)
[20:57:33 ERROR]: net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[20:57:33 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[20:57:33 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[20:57:33 ERROR]: java.lang.Thread.run(Thread.java:748)
[20:57:33 ERROR]: ------------------------------
[20:57:33 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:57:33 ERROR]: ------------------------------
[20:57:38 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:57:38 ERROR]: The server has not responded for 30 seconds! Creating thread dump
[20:57:38 ERROR]: ------------------------------
[20:57:38 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[20:57:38 ERROR]: ------------------------------
[20:57:38 ERROR]: Current Thread: Server thread
[20:57:38 ERROR]: PID: 22 | Suspended: false | Native: false | State: RUNNABLE
[20:57:38 ERROR]: Stack:
[20:57:38 ERROR]: org.bukkit.craftbukkit.v1_12_R1.util.WeakCollection$1.hasNext(WeakCollection.java:81)
[20:57:38 ERROR]: org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftScoreboardManager.getScoreboardScores(CraftScoreboardManager.java:104)
[20:57:38 ERROR]: net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:429)
[20:57:38 ERROR]: net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:366)
[20:57:38 ERROR]: net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:145)
[20:57:38 ERROR]: net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273)
[20:57:38 ERROR]: net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
[20:57:38 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948)
[20:57:38 ERROR]: net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[20:57:38 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[20:57:38 ERROR]: net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[20:57:38 ERROR]: java.lang.Thread.run(Thread.java:748)
[20:57:38 ERROR]: ------------------------------
[20:57:38 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:57:38 ERROR]: ------------------------------
[20:57:40 INFO]: React Supersampler has crashed. Reloading React.
[20:57:40 INFO]: SS has not responded for over 31.41s
[20:57:40 INFO]: LeRoche issued server command: /re
[20:57:40 INFO]: LeRoche issued server command: /re lag
```

**Comment by SwiftSwamp** [comment] 2019-08-15 05:22
Closing as this was likely fixed in the latest updates... and the issue is old. Please reopen if the issue continues.

**Closed by SwiftSwamp** 2019-08-15 05:22 UTC
Labels: 1.13, bug
