### ISSUE TITLE
Bugged chunk at world made with MultiVerse

### ISSUE THREAD

**Issue by onemoreplays** [VolmitSoftware/React#334] opened 2018-05-07 19:01 UTC
Hello,
so today I made world with MultiVerse (not only one actually) and this happened on every single one.
https://www.youtube.com/watch?v=dbgqx0nPZVg
As you can see, when I disable React and reload world, chunk is okay.
Hopefully you will be able to repair it.
Thanks and have a nice day,
inao

**Comment by lucas2107** [comment] 2018-05-07 21:43
Duplicate of #260

**Closed by lucas2107** 2018-05-07 21:43 UTC
