### ISSUE TITLE
React failing actions

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#380] opened 2018-06-03 10:14 UTC
Sometimes, and this is happening randomly, actions are blocked, no output in chat.
If you reload React, it work again.

Paper 1.8.8
React 6.554

**Comment by cyberpwnn** [comment] 2018-06-09 07:45
Cannot reproduce on paper 1.8.8. Need conditions or some sort of setup to find the issue. It may seem random but there is usually an unknown metric that needs to change to cause it.

**Comment by Rbot48** [comment] 2018-06-09 22:05
I am having the same problem with Paper 1.10.2.
React seems to disable itself, or at least some part of it, after some time. My server is online for 13 hours now.
I can't type any of the /re act [...] commands, not even /re a dump. There's no output. 
The automatic goals aren't working either.

**Comment by lucas2107** [comment] 2018-06-09 23:12
@Rbot48 /re reload is solving the problem? ( need to wait few seconds before React doing goals )

**Comment by Rbot48** [comment] 2018-06-09 23:15
@lucas2107 Yes, reloading with /re reload or restarting the server solves the problem. :)

**Comment by lucas2107** [comment] 2018-06-16 21:57
It seems to be after few minutes (like 3-4 minutes), actions aren't working and I need to reload the plugin to make it work.

**Comment by cyberpwnn** [comment] 2018-06-17 12:04
When it isnt working, do /re dump 

Also when it isnt working use /re a q

**Comment by lucas2107** [comment] 2018-06-17 15:02
![screenshot_1](https://user-images.githubusercontent.com/11612016/41509172-3f9a6852-7250-11e8-8772-03336ce40c2f.png)

**Comment by cyberpwnn** [comment] 2018-06-17 15:53
Use `/re a q x`

Then use `/re a pc @c:this`

(wait 10 seconds)

Then use `/re a q`

Then screenshot

**Comment by lucas2107** [comment] 2018-06-17 17:48
When I 
![screenshot_2](https://user-images.githubusercontent.com/11612016/41510568-4d00153e-7267-11e8-84f2-01254d27a749.png)

First command: /re a q
Then /re a q x
Then /re a pc @c:this
Then /re a q

**Comment by cyberpwnn** [comment] 2018-06-19 09:30
So your queue was just SUPER backed up. Hmmmm ill speed up action firing. Try and see if a certain action takes a long time to run.

**Comment by cyberpwnn** [comment] 2018-06-19 09:33
Rai will not queue 2 actions of the same type if a previous action is already queued. Fixed in 6.559

**Comment by lucas2107** [comment] 2018-06-19 13:15
Problem still happening...

**Comment by lucas2107** [comment] 2018-06-19 13:20
![screenshot_1](https://user-images.githubusercontent.com/11612016/41599714-47b35fdc-73d4-11e8-9cd0-f3d6097fcb1e.png)

**Comment by cyberpwnn** [comment] 2018-06-19 17:21
Ok first turn off the locking goals, how long is it taking to complete the actions?

**Comment by lucas2107** [comment] 2018-06-20 21:09
Seems to be hopper locking who was fcking the action queue.

I don't know why... When I run the command manually it's working, but if it's launched by React, it's not working.

**Comment by cyberpwnn** [comment] 2018-06-22 01:28
Ive put a cap on locking actions to help prevent them from bloating the queue. Test on 6.561

**Comment by lucas2107** [comment] 2018-06-22 10:30
Testing it

**Comment by cyberpwnn** [comment] 2018-06-25 23:51
Unable to reproduce

**Comment by Frerduro** [comment] 2018-07-06 18:52
Having this happen on spigot 1.12.2

**Comment by cyberpwnn** [comment] 2018-07-07 20:13
The world Avalon has a lot of entities.

**Comment by Frerduro** [comment] 2018-07-07 23:16
yes it does but its a very big world

**Comment by cyberpwnn** [comment] 2018-07-08 02:46
And notch decided to go with a chunk system

**Closed** 2018-07-25 12:11 UTC
Labels: blocked, bug, high priority
