### ISSUE TITLE
React disabling itself on startup

### ISSUE THREAD

**Issue by TheWranger** [VolmitSoftware/React#372] opened 2018-05-28 04:41 UTC
Sometimes React boots up just fine, other times it disables itself.
Error is varying in size (different amounts of "generated an exception while executing task" errors).

https://pastebin.com/CWSrtxvN

**Comment by lucas2107** [comment] 2018-05-28 05:32
Try using the latest version of React.

**Comment by TheWranger** [comment] 2018-05-28 06:57
Haven't gotten the issue (yet) in the newest version. I'll close this for now and reopen if the issue arises again.

**Comment by TheWranger** [comment] 2018-05-28 10:05
https://pastebin.com/1KQfxPqX
Can confirm now that this does happen in the latest build.

**Comment by cyberpwnn** [comment] 2018-05-28 13:49
What is happening before the first line in your paste?

**Comment by TheWranger** [comment] 2018-05-29 03:33
Here's a full server log of the most recent time it's happened.
https://pastebin.com/BLzeRaA9
This is from when I was updating my plugin Minator to the latest version.

**Comment by cyberpwnn** [comment] 2018-05-30 01:05
Could you set `listen-channels-enabled: true` so we can see what could have caused it? Still unable to reproduce :/

**Comment by TheWranger** [comment] 2018-05-31 09:10
Enabled `listen-channels-enabled`, here's the results:
https://pastebin.com/nhrAbBhW

**Comment by cyberpwnn** [comment] 2018-06-01 03:34
Fixed in 6.553
The problem was the remote server is attempting to shut down (react remote) and was attempting to queue an async task, however the task was routed through bukkit since react was busy. Instead it spawns up its own killer thread to solve this.

**Closed by cyberpwnn** 2018-06-01 03:34 UTC
Labels: bug
